[build]
  # Build command with relaxed TypeScript checks
  command = "npm run build:deploy"
  
  # Directory to publish (Vite builds to 'dist')
  publish = "dist"

# Environment variables
[context.production.environment]
  CI = "false"
  
# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 